###################################################################

# Created by write_sdc on Sun Nov 30 07:59:13 2025

###################################################################
set sdc_version 2.1

set_units -time ns -resistance kOhm -capacitance pF -voltage V -current mA
set_wire_load_mode top
set_load -pin_load 0.05 [get_ports out_valid]
set_load -pin_load 0.05 [get_ports {out[31]}]
set_load -pin_load 0.05 [get_ports {out[30]}]
set_load -pin_load 0.05 [get_ports {out[29]}]
set_load -pin_load 0.05 [get_ports {out[28]}]
set_load -pin_load 0.05 [get_ports {out[27]}]
set_load -pin_load 0.05 [get_ports {out[26]}]
set_load -pin_load 0.05 [get_ports {out[25]}]
set_load -pin_load 0.05 [get_ports {out[24]}]
set_load -pin_load 0.05 [get_ports {out[23]}]
set_load -pin_load 0.05 [get_ports {out[22]}]
set_load -pin_load 0.05 [get_ports {out[21]}]
set_load -pin_load 0.05 [get_ports {out[20]}]
set_load -pin_load 0.05 [get_ports {out[19]}]
set_load -pin_load 0.05 [get_ports {out[18]}]
set_load -pin_load 0.05 [get_ports {out[17]}]
set_load -pin_load 0.05 [get_ports {out[16]}]
set_load -pin_load 0.05 [get_ports {out[15]}]
set_load -pin_load 0.05 [get_ports {out[14]}]
set_load -pin_load 0.05 [get_ports {out[13]}]
set_load -pin_load 0.05 [get_ports {out[12]}]
set_load -pin_load 0.05 [get_ports {out[11]}]
set_load -pin_load 0.05 [get_ports {out[10]}]
set_load -pin_load 0.05 [get_ports {out[9]}]
set_load -pin_load 0.05 [get_ports {out[8]}]
set_load -pin_load 0.05 [get_ports {out[7]}]
set_load -pin_load 0.05 [get_ports {out[6]}]
set_load -pin_load 0.05 [get_ports {out[5]}]
set_load -pin_load 0.05 [get_ports {out[4]}]
set_load -pin_load 0.05 [get_ports {out[3]}]
set_load -pin_load 0.05 [get_ports {out[2]}]
set_load -pin_load 0.05 [get_ports {out[1]}]
set_load -pin_load 0.05 [get_ports {out[0]}]
create_clock [get_ports clk]  -period 28  -waveform {0 14}
set_input_delay -clock clk  0  [get_ports clk]
set_input_delay -clock clk  0  [get_ports rst_n]
set_input_delay -clock clk  14  [get_ports in_valid_d]
set_input_delay -clock clk  14  [get_ports in_valid_t]
set_input_delay -clock clk  14  [get_ports in_valid_w1]
set_input_delay -clock clk  14  [get_ports in_valid_w2]
set_input_delay -clock clk  14  [get_ports {data_point[31]}]
set_input_delay -clock clk  14  [get_ports {data_point[30]}]
set_input_delay -clock clk  14  [get_ports {data_point[29]}]
set_input_delay -clock clk  14  [get_ports {data_point[28]}]
set_input_delay -clock clk  14  [get_ports {data_point[27]}]
set_input_delay -clock clk  14  [get_ports {data_point[26]}]
set_input_delay -clock clk  14  [get_ports {data_point[25]}]
set_input_delay -clock clk  14  [get_ports {data_point[24]}]
set_input_delay -clock clk  14  [get_ports {data_point[23]}]
set_input_delay -clock clk  14  [get_ports {data_point[22]}]
set_input_delay -clock clk  14  [get_ports {data_point[21]}]
set_input_delay -clock clk  14  [get_ports {data_point[20]}]
set_input_delay -clock clk  14  [get_ports {data_point[19]}]
set_input_delay -clock clk  14  [get_ports {data_point[18]}]
set_input_delay -clock clk  14  [get_ports {data_point[17]}]
set_input_delay -clock clk  14  [get_ports {data_point[16]}]
set_input_delay -clock clk  14  [get_ports {data_point[15]}]
set_input_delay -clock clk  14  [get_ports {data_point[14]}]
set_input_delay -clock clk  14  [get_ports {data_point[13]}]
set_input_delay -clock clk  14  [get_ports {data_point[12]}]
set_input_delay -clock clk  14  [get_ports {data_point[11]}]
set_input_delay -clock clk  14  [get_ports {data_point[10]}]
set_input_delay -clock clk  14  [get_ports {data_point[9]}]
set_input_delay -clock clk  14  [get_ports {data_point[8]}]
set_input_delay -clock clk  14  [get_ports {data_point[7]}]
set_input_delay -clock clk  14  [get_ports {data_point[6]}]
set_input_delay -clock clk  14  [get_ports {data_point[5]}]
set_input_delay -clock clk  14  [get_ports {data_point[4]}]
set_input_delay -clock clk  14  [get_ports {data_point[3]}]
set_input_delay -clock clk  14  [get_ports {data_point[2]}]
set_input_delay -clock clk  14  [get_ports {data_point[1]}]
set_input_delay -clock clk  14  [get_ports {data_point[0]}]
set_input_delay -clock clk  14  [get_ports {target[31]}]
set_input_delay -clock clk  14  [get_ports {target[30]}]
set_input_delay -clock clk  14  [get_ports {target[29]}]
set_input_delay -clock clk  14  [get_ports {target[28]}]
set_input_delay -clock clk  14  [get_ports {target[27]}]
set_input_delay -clock clk  14  [get_ports {target[26]}]
set_input_delay -clock clk  14  [get_ports {target[25]}]
set_input_delay -clock clk  14  [get_ports {target[24]}]
set_input_delay -clock clk  14  [get_ports {target[23]}]
set_input_delay -clock clk  14  [get_ports {target[22]}]
set_input_delay -clock clk  14  [get_ports {target[21]}]
set_input_delay -clock clk  14  [get_ports {target[20]}]
set_input_delay -clock clk  14  [get_ports {target[19]}]
set_input_delay -clock clk  14  [get_ports {target[18]}]
set_input_delay -clock clk  14  [get_ports {target[17]}]
set_input_delay -clock clk  14  [get_ports {target[16]}]
set_input_delay -clock clk  14  [get_ports {target[15]}]
set_input_delay -clock clk  14  [get_ports {target[14]}]
set_input_delay -clock clk  14  [get_ports {target[13]}]
set_input_delay -clock clk  14  [get_ports {target[12]}]
set_input_delay -clock clk  14  [get_ports {target[11]}]
set_input_delay -clock clk  14  [get_ports {target[10]}]
set_input_delay -clock clk  14  [get_ports {target[9]}]
set_input_delay -clock clk  14  [get_ports {target[8]}]
set_input_delay -clock clk  14  [get_ports {target[7]}]
set_input_delay -clock clk  14  [get_ports {target[6]}]
set_input_delay -clock clk  14  [get_ports {target[5]}]
set_input_delay -clock clk  14  [get_ports {target[4]}]
set_input_delay -clock clk  14  [get_ports {target[3]}]
set_input_delay -clock clk  14  [get_ports {target[2]}]
set_input_delay -clock clk  14  [get_ports {target[1]}]
set_input_delay -clock clk  14  [get_ports {target[0]}]
set_input_delay -clock clk  14  [get_ports {weight1[31]}]
set_input_delay -clock clk  14  [get_ports {weight1[30]}]
set_input_delay -clock clk  14  [get_ports {weight1[29]}]
set_input_delay -clock clk  14  [get_ports {weight1[28]}]
set_input_delay -clock clk  14  [get_ports {weight1[27]}]
set_input_delay -clock clk  14  [get_ports {weight1[26]}]
set_input_delay -clock clk  14  [get_ports {weight1[25]}]
set_input_delay -clock clk  14  [get_ports {weight1[24]}]
set_input_delay -clock clk  14  [get_ports {weight1[23]}]
set_input_delay -clock clk  14  [get_ports {weight1[22]}]
set_input_delay -clock clk  14  [get_ports {weight1[21]}]
set_input_delay -clock clk  14  [get_ports {weight1[20]}]
set_input_delay -clock clk  14  [get_ports {weight1[19]}]
set_input_delay -clock clk  14  [get_ports {weight1[18]}]
set_input_delay -clock clk  14  [get_ports {weight1[17]}]
set_input_delay -clock clk  14  [get_ports {weight1[16]}]
set_input_delay -clock clk  14  [get_ports {weight1[15]}]
set_input_delay -clock clk  14  [get_ports {weight1[14]}]
set_input_delay -clock clk  14  [get_ports {weight1[13]}]
set_input_delay -clock clk  14  [get_ports {weight1[12]}]
set_input_delay -clock clk  14  [get_ports {weight1[11]}]
set_input_delay -clock clk  14  [get_ports {weight1[10]}]
set_input_delay -clock clk  14  [get_ports {weight1[9]}]
set_input_delay -clock clk  14  [get_ports {weight1[8]}]
set_input_delay -clock clk  14  [get_ports {weight1[7]}]
set_input_delay -clock clk  14  [get_ports {weight1[6]}]
set_input_delay -clock clk  14  [get_ports {weight1[5]}]
set_input_delay -clock clk  14  [get_ports {weight1[4]}]
set_input_delay -clock clk  14  [get_ports {weight1[3]}]
set_input_delay -clock clk  14  [get_ports {weight1[2]}]
set_input_delay -clock clk  14  [get_ports {weight1[1]}]
set_input_delay -clock clk  14  [get_ports {weight1[0]}]
set_input_delay -clock clk  14  [get_ports {weight2[31]}]
set_input_delay -clock clk  14  [get_ports {weight2[30]}]
set_input_delay -clock clk  14  [get_ports {weight2[29]}]
set_input_delay -clock clk  14  [get_ports {weight2[28]}]
set_input_delay -clock clk  14  [get_ports {weight2[27]}]
set_input_delay -clock clk  14  [get_ports {weight2[26]}]
set_input_delay -clock clk  14  [get_ports {weight2[25]}]
set_input_delay -clock clk  14  [get_ports {weight2[24]}]
set_input_delay -clock clk  14  [get_ports {weight2[23]}]
set_input_delay -clock clk  14  [get_ports {weight2[22]}]
set_input_delay -clock clk  14  [get_ports {weight2[21]}]
set_input_delay -clock clk  14  [get_ports {weight2[20]}]
set_input_delay -clock clk  14  [get_ports {weight2[19]}]
set_input_delay -clock clk  14  [get_ports {weight2[18]}]
set_input_delay -clock clk  14  [get_ports {weight2[17]}]
set_input_delay -clock clk  14  [get_ports {weight2[16]}]
set_input_delay -clock clk  14  [get_ports {weight2[15]}]
set_input_delay -clock clk  14  [get_ports {weight2[14]}]
set_input_delay -clock clk  14  [get_ports {weight2[13]}]
set_input_delay -clock clk  14  [get_ports {weight2[12]}]
set_input_delay -clock clk  14  [get_ports {weight2[11]}]
set_input_delay -clock clk  14  [get_ports {weight2[10]}]
set_input_delay -clock clk  14  [get_ports {weight2[9]}]
set_input_delay -clock clk  14  [get_ports {weight2[8]}]
set_input_delay -clock clk  14  [get_ports {weight2[7]}]
set_input_delay -clock clk  14  [get_ports {weight2[6]}]
set_input_delay -clock clk  14  [get_ports {weight2[5]}]
set_input_delay -clock clk  14  [get_ports {weight2[4]}]
set_input_delay -clock clk  14  [get_ports {weight2[3]}]
set_input_delay -clock clk  14  [get_ports {weight2[2]}]
set_input_delay -clock clk  14  [get_ports {weight2[1]}]
set_input_delay -clock clk  14  [get_ports {weight2[0]}]
set_output_delay -clock clk  14  [get_ports out_valid]
set_output_delay -clock clk  14  [get_ports {out[31]}]
set_output_delay -clock clk  14  [get_ports {out[30]}]
set_output_delay -clock clk  14  [get_ports {out[29]}]
set_output_delay -clock clk  14  [get_ports {out[28]}]
set_output_delay -clock clk  14  [get_ports {out[27]}]
set_output_delay -clock clk  14  [get_ports {out[26]}]
set_output_delay -clock clk  14  [get_ports {out[25]}]
set_output_delay -clock clk  14  [get_ports {out[24]}]
set_output_delay -clock clk  14  [get_ports {out[23]}]
set_output_delay -clock clk  14  [get_ports {out[22]}]
set_output_delay -clock clk  14  [get_ports {out[21]}]
set_output_delay -clock clk  14  [get_ports {out[20]}]
set_output_delay -clock clk  14  [get_ports {out[19]}]
set_output_delay -clock clk  14  [get_ports {out[18]}]
set_output_delay -clock clk  14  [get_ports {out[17]}]
set_output_delay -clock clk  14  [get_ports {out[16]}]
set_output_delay -clock clk  14  [get_ports {out[15]}]
set_output_delay -clock clk  14  [get_ports {out[14]}]
set_output_delay -clock clk  14  [get_ports {out[13]}]
set_output_delay -clock clk  14  [get_ports {out[12]}]
set_output_delay -clock clk  14  [get_ports {out[11]}]
set_output_delay -clock clk  14  [get_ports {out[10]}]
set_output_delay -clock clk  14  [get_ports {out[9]}]
set_output_delay -clock clk  14  [get_ports {out[8]}]
set_output_delay -clock clk  14  [get_ports {out[7]}]
set_output_delay -clock clk  14  [get_ports {out[6]}]
set_output_delay -clock clk  14  [get_ports {out[5]}]
set_output_delay -clock clk  14  [get_ports {out[4]}]
set_output_delay -clock clk  14  [get_ports {out[3]}]
set_output_delay -clock clk  14  [get_ports {out[2]}]
set_output_delay -clock clk  14  [get_ports {out[1]}]
set_output_delay -clock clk  14  [get_ports {out[0]}]
